name: Test Environment

on: 
  workflow_dispatch:

jobs:
    get_path:
        runs-on: windows-latest
        name: Test
        steps:
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Test
              run: |
                where python
                python -c "import sys; print(sys.executable)"
              shell: cmd
